controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    zsmall_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


zsmall_controller:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names  : ['wheel_left_joint']
    right_wheel_names : ['wheel_right_joint']

    publish_rate: 50.0               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

    wheel_separation : 0.445 # .445 = 17.5 inches
    wheel_radius : 0.063 # .063 = 2.5 inch radius

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.2

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    # Publish limited velocity
    publish_limited_velocity: true

    # Publish wheel data
    publish_wheel_data: true

    # Publish to TF directly or not  ** 11/6 was true
    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s was 0.7
        min_velocity           : -1.0 # m/s was -0.7
        has_acceleration_limits: true
        max_acceleration       : 0.25  # m/s^2
        min_acceleration       : -0.25 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 3.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.5  # rad/s was 8.5
        min_velocity           : -1.5  # rad/s was -8.5
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0   # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 1.0  # rad/s^3


simple_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint