joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min  : 0.2
      linear_forward_max  : 0.2 # was .7
      linear_backward_min : 0.2
      linear_backward_max : 0.2 # was .2
      angular_min : 0.2 # was .7
      angular_max : 1.0 # was 5.
      steps       : 3